### ISSUE TITLE
Non-OSS tableauhyperapi dependency

### ISSUE THREAD

**Issue by jayvdb** [tableau/hyper-api-samples#10]
This project depends on tableauhyperapi , which is not OSS.
see https://github.com/tableau/server-client-python/issues/594

This should be clearly explained in the README and ideally also a note at the top of the LICENSE file that while the samples are MIT licensed, they are tightly coupled with a non-OSS Python library.

**Comment by tsjoblad** [comment]
Hi jayvdb, this is being reviewed by our team. Thanks for opening the issue.

**Comment by jonas-eckhardt** [comment]
Sorry for the long delay. We updated the top-level readme file.
