### ISSUE TITLE
will hyper release the arrch64 linux version?

### ISSUE THREAD

**Issue by l1t1** [tableau/hyper-api-samples#100]
https://tableau.github.io/hyper-db/docs/releases/ shows only x64 version.

**Comment by vogelsgesang** [comment]
We are working on an Apple-Silicon version of Hyper API. It should arrive later this year.
There are currently no plans for a Graviton version Hyper API (or any other ARM based architectures)

**Comment by l1t1** [comment]
thanks.

**Comment by lorepirri** [comment]
Hi @l1t1 any updates for Linux/aarch64 releases?
