### ISSUE TITLE
add additional command before building for .net

### ISSUE THREAD

**Issue by hungarianguy** [tableau/hyper-api-samples#12]
for DotNet build commands (build.bat / build.sh) I recommend you add the following like
          dotnet add package Tableau.HyperAPI.NET
before you do
          dotnet build Example.csproj

otherwise some people that just git cloned this to their machine do not have required references.

**Comment by jonas-eckhardt** [comment]
Hi @hungarianguy, thanks for reporting. Can you provide some more information about the error that you are seeing when running into this defect?

**Comment by jonas-eckhardt** [comment]
Thanks again. We'll have a look at it and come back to you.

**Comment by roediger** [comment]
I could reproduce the issue and created a pull request with a fix.
