### ISSUE TITLE
Failed to import tableauhyperapi in virtual environment 

### ISSUE THREAD

**Issue by gargantr** [tableau/hyper-api-samples#14]
When I tried to run my app in virtual environment with tableau hyper api. I hit this error. Please take a look at the below error message:

`/Users/sfsdf/developer/Tabloader/tabloader-env/lib/python3.7/site-packages/tableauhyperapi/impl/dll.py:24: UserWarning: Failed to import cdef_compiled module, importing tableauhyperapi will be slow. Please report this to Tableau. Error message was: dlopen(/Users/dsfsd/developer/Tabloader/tabloader-env/lib/python3.7/site-packages/_cffi_backend.cpython-37m-darwin.so, 2): Library not loaded: /usr/local/opt/libffi/lib/libffi.7.dylib
  Referenced from: /Users/asdasd/developer/Tabloader/tabloader-env/lib/python3.7/site-packages/_cffi_backend.cpython-37m-darwin.so
  Reason: image not found
  warnings.warn(f'Failed to import cdef_compiled module, importing tableauhyperapi will be slow. Please report this to '
Traceback (most recent call last):
  File "/Users/dasd/developer/Tabloader/tabloader-env/lib/python3.7/site-packages/tableauhyperapi/impl/dll.py", line 19, in <module>
    from .cdef_compiled import ffi
  File "/Users/sadd/developer/Tabloader/tabloader-env/lib/python3.7/site-packages/tableauhyperapi/impl/cdef_compiled.py", line 13, in <module>
    import _cffi_backend
ImportError: dlopen(/Users/dasd/developer/Tabloader/tabloader-env/lib/python3.7/site-packages/_cffi_backend.cpython-37m-darwin.so, 2): Library not loaded: /usr/local/opt/libffi/lib/libffi.7.dylib
  Referenced from: /Users/dasd/developer/Tabloader/tabloader-env/lib/python3.7/site-packages/_cffi_backend.cpython-37m-darwin.so
  Reason: image not found
`

**Comment by jonas-eckhardt** [comment]
This may be related to an issue with the cffi library version 1.14.3 which got "yanked" (see https://pypi.org/project/cffi/#history). Can you try to 
`pip uninstall tableauhyperapi`
`pip uninstall cffi`

and then reinstall it with 
`pip install tableauhyperapi`

**Comment by gargantr** [comment]
Hi Jonas, thanks for getting back to me. I wasn't using that cffi version, but I was able to fix it one I rebuild my virtual environment.

**Comment by jonas-eckhardt** [comment]
Great! Thanks for letting me know. I'm going to close the defect.
