### ISSUE TITLE
java.lang.RuntimeException: Failed to start a new Hyper instance. The Hyper executable "<path>/hyper/hyperd" does not exist.

### ISSUE THREAD

**Issue by tooptoop4** [tableau/hyper-api-samples#22]
Following https://github.com/tableau/hyper-api-samples/tree/main/Tableau-Supported/Java/read-and-print-data-from-existing-hyper-file

getting this error:
```java.lang.RuntimeException: Failed to start a new Hyper instance. The Hyper executable "<path>/hyper/hyperd" does not exist.```

Is there some hyperd binary I need to install/run? I don't have tableau installed but I want to read a hyper file in java

**Comment by vogelsgesang** [comment]
The hyperd binary should have been part of the HyperAPI library itself. The .jar file comes with the necessary "hyperd" executable...

It's surprising and concerning that this didn't work in your case.

Could you provide us some repro instructions? E.g., how exactly did you install HyperAPI? which version? How did you build the example? Which operating system? ...

**Comment by tooptoop4** [comment]
downloaded tableauhyperapi-java-macos-x86_64-release-hyperapi_release_15.0.0.11952.ra70a9982 and unzipped
code is https://github.com/tableau/hyper-api-samples/tree/main/Tableau-Supported/Java/read-and-print-data-from-existing-hyper-file
hyperapi-15.0.0.11952.jar and hyperapioslib-15.0.0.11952.jar on class path (not on maven central is annoying :( )
mvn build with:
<dependency>
            <groupId>com.tableau</groupId>
            <artifactId>hyperapi</artifactId>
            <version>15.0.0.11952</version>
            <scope>system</scope>
            <systemPath>/mypath/tableauhyperapi-java-macos-x86_64-release-hyperapi_release_15.0.0.11952.ra70a9982/lib/tableauhyperapi.jar</systemPath>
        </dependency>
        <dependency>
            <groupId>com.tableau</groupId>
            <artifactId>hyperapioslib</artifactId>
            <version>15.0.0.11952</version>
            <scope>system</scope>
            <systemPath>/mypath/tableauhyperapi-java-macos-x86_64-release-hyperapi_release_15.0.0.11952.ra70a9982/lib/</systemPath>
        </dependency>

OS is Mac Big Sur

**Comment by dmakreshanski** [comment]
I can't say exactly what is happening in your case with maven, I can just try to give a bit more information on this topic.
I could run the example with gradle running `gradle build` and `gradle run` inside `Tableau-Supported/Java/read-and-print-data-from-existing-hyper-file`. I just modified the dependency path inside `build.gradle` to: `/mypath/tableauhyperapi-java-macos-x86_64-release-hyperapi_release_15.0.0.11952.ra70a9982/lib`

Note that the `hyperd` executable is provided with the HyperAPI library:

`ls tableauhyperapi-java-macos-x86_64-release-hyperapi_release_15.0.0.11952.ra70a9982/lib/hyper 
hyperd		hyperdstarter
`

The `HyperProcess` class that is part of the API can take as argument a path where to look for the hyperd file. In this example the path is not provided and it will try to locate the binary. You can see in the error where it's trying to locate it.

You can either link the `hyper` folder inside `/mypath/tableauhyperapi-java-macos-x86_64-release-hyperapi_release_15.0.0.11952.ra70a9982/lib/` or edit the example .java file and provide the path to `HyperProcess` (https://help.tableau.com/current/api/hyper_api/en-us/reference/java/index.html)

**Comment by tooptoop4** [comment]
"The HyperProcess class that is part of the API can take as argument a path where to look for the hyperd file." works for me
