### ISSUE TITLE
Support for R

### ISSUE THREAD

**Issue by EricBartha** [tableau/hyper-api-samples#24]
Is there any support for R (officially or unofficially)? I do most of my data analysis projects in R and would like to update the .hyper file feeding my Tableau dashboard directly from R.

If not, is there any documentation I should reference should I want to make my own R package to help with this?

Thank you!

**Comment by tsjoblad** [comment]
Hey Eric--so although we don't have a call to import data from R directly (like we do with csv), the Hyper API doesn't really care where data comes from. If you wanted to read from dataframes to hyper files, it's pretty easy. I'd highly recommend the library [pantab](https://pantab.readthedocs.io/en/latest/)!

You'll still need to set up a script to schedule the processes, but this should take a lot of the work out of it.

Let me know if this makes sense or if I missed something.
Tucker

**Comment by vogelsgesang** [comment]
[pantabR](https://github.com/Btibert3/pantabR) looks like a viable solution. It is an R wrapper around the pantab library already suggested by @tsjoblad.

I have no experience with it, and just learned about its existence myself...
Thanks, @Btibert3, for creating pantabR! :)

**Comment by vogelsgesang** [comment]
also, there is https://github.com/zhiruiwang/RTableau ...
Thanks, @zhiruiwang! :)

**Comment by EricBartha** [comment]
Thank you, @tsjoblad. I'll look into that package.
