### ISSUE TITLE
What is the max size of hyperfile upload support? 

### ISSUE THREAD

**Issue by Terry93** [tableau/hyper-api-samples#25]
Hi question regarding https://github.com/tableau/hyper-api-samples/tree/main/Community-Supported/publish-hyper where it shows how to create only one hyper file and upload to Tableau server. I am trying to do the same: I have 30G of CSV data on s3, I am planning to download it locally, and convert them to hyper files.

Question:

1. can I break my table's data into several hyper files and upload to Tableau server separately?
2. what is the max size of hyper file can be uploaded from local to Tableau server? assuming I am using the python client.

Thanks!

**Comment by tsjoblad** [comment]
Hey--I don't think there's a max size TSC can handle. From TSC's doc:

> This method checks the size of the data source and automatically determines whether the publish the data source in multiple parts or in one operation.

Additionally, the below examples should help get you started with Multi-Table publishing and working with S3 data:
- https://github.com/tableau/hyper-api-samples/tree/main/Community-Supported/publish-multi-table-hyper
- https://github.com/tableau/hyper-api-samples/tree/main/Community-Supported/s3-to-hyper

Let me know if you have any further questions!

**Comment by Terry93** [comment]
@tsjoblad thank you for your quick response! I will take a look! Thanks again!

**Comment by tsjoblad** [comment]
Sure thing, feel free to reopen if you want to talk about either!
