### ISSUE TITLE
Alteryx Workflow - Python tool - Read Hyper file

### ISSUE THREAD

**Issue by nakukavali** [tableau/hyper-api-samples#26]
I come across a requirement to read Hyper files from our Online Tableau environment as a source in Alteryx Workflow.
I read through the documentation and examples. I could not figure out the following.

Does Python tool in Alteryx be able to read a hyper file online Tableau?
How to set the location of a hyper file which is in Online Tableau.

Thank you.

**Comment by jonas-eckhardt** [comment]
Hi @nakukavali, 

starting with version Alteryx 2019.4, you can read .hyper files directly in Alteryx (https://community.alteryx.com/t5/Analytics/See-What-all-the-Hype-s-About-in-2019-4/ba-p/491437). 

> Does Python tool in Alteryx be able to read a hyper file online Tableau?
This question can probably be answered best by the Alteryx support team. If Alteryx allows to install and execute any Python library, that should be possible. However, I am not an expert here. 

> How to set the location of a hyper file which is in Online Tableau?
You cannot directly access a .hyper file from Tableau Online. You need to use the REST API (for Python just use the tableauserverclient library (https://tableau.github.io/server-client-python/docs/)) to download the file. Then, you can access it.

Please let me know if you have further questions.
Thanks
Jonas

**Comment by nakukavali** [comment]
Hi @jonas-eckhardt,
Thank you for the detailed reply and good set of examples and documentation provided here.
We are using Alteryx 2020.3 and I am aware of the functionality to read (local) hyper files directly.

I am trying to find a solution to read Hyper files from Online Tableau and also do some SQL to limit the data I read, for better  performance. I will review the links you updated.

Thank you.

**Comment by jonas-eckhardt** [comment]
@nakukavali can we close this issue or do you have further questions?
