### ISSUE TITLE
Hyper API Copy from csv to hyper failed with Context: 0x5fdfad59 without explaining details

### ISSUE THREAD

**Issue by Terry93** [tableau/hyper-api-samples#27]
My python script used Hyper API Copy from csv to hyper and it failed with Context: 0x5fdfad59 without telling me more details. Here is the stack trace:

```
  File "/usr/local/lib/python3.7/dist-packages/tableauhyperapi/connection.py", line 230, in execute_command
    row_count_cdata))
  File "/usr/local/lib/python3.7/dist-packages/tableauhyperapi/impl/dllutil.py", line 110, in check
    raise errp.to_exception()
tableauhyperapi.hyperexception.HyperException: 
Context: 0x5fdfad59
```

versions that I am using
```
tableauhyperapi==0.0.11889
tableauserverclient==0.12
```
I do see some discussions in the tableau community about 0x5fdfad59 error but I think I have a different case:
 

1. the error is happening on company's production environment and I can't reproduce it locally (it runs fine locally). I have checked the package versions they should be correct.
2. this error only tells me Context: 0x5fdfad59 while I see error message from other posts will have exact lines and columns that have issue.
 
Do you have idea on how to debug this? thanks!

**Comment by jkammerer** [comment]
Hello,

Let's discuss this issue in the [HAPI forums](https://community.tableau.com/s/question/0D54T00000YslRASAZ/hyper-api-copy-from-csv-to-hyper-failed-with-context-0x5fdfad59-without-explaining-details).
