### ISSUE TITLE
Publishing of multi-tables not working

### ISSUE THREAD

**Issue by shomavg** [tableau/hyper-api-samples#29]
Hello,
Has anyone got his working? https://github.com/tableau/hyper-api-samples/tree/main/Community-Supported/publish-multi-table-hyper
I have tried the exact solution but the it is still publishes the old hyper file and not the new one. Can someone here help me out please?

Shoma

**Comment by tsjoblad** [comment]
Hi Shoma--can either share the code or describe how you are creating the new .hyper file to swap? The sample creates a dummy hyper file, you will need to implement your own code to load the new data in.

Let me know! Thanks

**Comment by shomavg** [comment]
Hello Tucker,

Thank you for getting back to me. At first, I am trying to run your sample code inside a Azure databricks. The new hyperfile created has an extra table in it. But when I publish the the hyperfile, i can only the older hyper file changes and not the new one.

Thanks,
Shoma

**Comment by tsjoblad** [comment]
Can you confirm that the swapping into the TDSX ([found here](https://github.com/tableau/hyper-api-samples/blob/main/Community-Supported/publish-multi-table-hyper/publish-multi-table-hyper.py#L98)) is working properly? 

I'd first try validating that you can get the new data source to contain the multi-table hyper file.

**Comment by shomavg** [comment]
Hello Tucker,

Apologies for the late reply.  Swapping into the TDSX is not happening. That is where I am having issues.

Thank you,
Shoma
