### ISSUE TITLE
Hyperfile within Azure databricks

### ISSUE THREAD

**Issue by shomavg** [tableau/hyper-api-samples#30]
Hello,

I am creating an hyperfile inside Azure databricks. I want the hyperfile created to be saved in Azure Blob storage. How and where can i configure to save the .hyper file?

**Comment by jonas-eckhardt** [comment]
Hi @shomavg, the hyper file is just a normal file, so you should be able to copy it to Azure Blob storage. If you need help with this, I think you should rather ask the Azure databricks support.
