### ISSUE TITLE
how to access `tableau-libs/hyper/hyperd` packaged in jar

### ISSUE THREAD

**Issue by xhudik** [tableau/hyper-api-samples#39]
Hi there,

I'm wondering, is there some standard/recommended way how to work with Tableau hyper library in Java world?
Basically, I need to pack Tableau Hyper lib in a jar file, publish to maven (as normal java lib/app) and then use it within some other app.

Imagine, I have library `a` with HyperAPI (and `hyperd` binary) published on my private maven. I'm developing project `b` that has `a` as a dependency. The problem is that I dont know how to access access binary `tableau-libs/hyper/hyperd` from package `b`.

error:
```
Cause: com.tableau.hyperapi.HyperException: The Hyper executable "/home/me/.m2/repository/a/0.3.1-pk009-SNAPSHOT/hyper/hyperd" does not exist.
```

Any idea how to proceed?

**Comment by jkammerer** [comment]
Hello,

You can explicitly pass the hyper executable as described here:
https://community.tableau.com/s/question/0D54T00000f6fYRSAY/building-hyper-api-java-project-for-linux-with-maven
