### ISSUE TITLE
inserting data from csv file into existing hyper file

### ISSUE THREAD

**Issue by ramananravishankar** [tableau/hyper-api-samples#46]
Hi, I'm creating a data frame & csv file from pulling data from a SQL data base and then write the same into an existing hyper file. But when ever I do it, it is just replacing the data in the hyper file rather then inserting new data along with the existing ones.

def create_hyper_file_from_csv(dataframe):

    print("Load data from CSV into table in new Hyper file for ACE Dashboard")

    process_parameters = {
        # Limits the number of Hyper event log files to two.
        "log_file_max_count": "2",
        # Limits the size of Hyper event log files to 100 megabytes.
        "log_file_size_limit": "100M"
    }

    with HyperProcess(Telemetry.DO_NOT_SEND_USAGE_DATA_TO_TABLEAU, 'Tabloader', parameters=process_parameters) as hyper:

        connection_parameters = {"lc_time": "en_US"}

        with Connection(endpoint=hyper.endpoint, database=PATH_TO_HYPER,
                        create_mode=CreateMode.CREATE_AND_REPLACE, parameters=connection_parameters) as connection:
            
            connection.catalog.create_table(ace_dashboard_table)

            with Inserter(connection, ace_dashboard_table) as inserter:
                for index, row in dataframe.iterrows():
                    try:
                        inserter.add_row(row)
                    except Exception as e:
                        print("An error occured at row {index}: {e}")
                
                inserter.execute()
                
            #insert_csv_data = connection.execute_command(
            # ) command=f"COPY {ace_dashboard_table.table_name} FROM {escape_string_literal(PATH_TO_CSV)} with "
            #    "(format csv, NULL 'NULL', delimiter ';', header true)")

        print("The connection to the Hyper file is closed.")
    #print(f"Loaded {insert_csv_data} rows.")
    os.remove(PATH_TO_CSV)

**Comment by jonas-eckhardt** [comment]
Hi @ramananravishankar, 

when creating the connection to the Hyper file, you specify

`create_mode=CreateMode.CREATE_AND_REPLACE`

which will create a new hyper file and replace the existing one. If you want to insert into the existing file, you need to just connect to the file and not create a new one. To do that, either use `CreateMode.NONE` (which will throw an error if the file does not exist) or `CreateMode.CREATE_IF_NOT_EXISTS` (which will create the file if it does not exist).

You can find the API reference here: https://help.tableau.com/current/api/hyper_api/en-us/reference/py/tableauhyperapi.html#api-reference

Cheers
Jonas

**Comment by ramananravishankar** [comment]
I have tried both of them earlier. It shows an error saying the file already exists and does not update with the new data.

**Comment by jonas-eckhardt** [comment]
Can you please try again. If it fails again, please attach the exact code you used + the output.

Thanks
Jonas

**Comment by ramananravishankar** [comment]
Below is the full code.

import mysql.connector
import pandas as pd
import csv
import os
import json
import sys
import datetime
from datetime import date, datetime, timedelta
from mysql.connector import Error
from tableauhyperapi import HyperProcess, Connection, TableDefinition, SqlType, Telemetry, Inserter, CreateMode, connection, \
    escape_string_literal, HyperException, NULLABLE, tabledefinition


PATH_TO_CSV = r"ACE_DB_Output_" + str(date.today()) + "_.csv"
#PATH_TO_HYPER = r"ACE_DB_Output_"+ str(date.today()) + "_.hyper"
PATH_TO_HYPER = r"ACE_DB_Output_.hyper"

ace_dashboard_table = TableDefinition(
    table_name="ACE_Dashboard",
    columns=[TableDefinition.Column('Customer', SqlType.text(), NULLABLE),
             TableDefinition.Column('JID', SqlType.text(), NULLABLE),
             TableDefinition.Column('JID_AID', SqlType.text(), NULLABLE),
             TableDefinition.Column('Rule', SqlType.text(), NULLABLE),
             TableDefinition.Column('Category', SqlType.text(), NULLABLE),
             TableDefinition.Column('Change_Type', SqlType.text(), NULLABLE),
             TableDefinition.Column('Find', SqlType.text(), NULLABLE),
             TableDefinition.Column('Replace', SqlType.text(), NULLABLE),
             TableDefinition.Column('Occurrences', SqlType.int(), NULLABLE),
             TableDefinition.Column('ProcessedDate', SqlType.date(), NULLABLE)
             ]
)

ACE_Data_Array = []

def load_config():
    try:
        with open('config.json', 'r') as f:
            config_file = json.load(f)
            print("Config file loaded.")
            return config_file
    except:
        message = "Could not read config file."
        print("Unexpected error: ", sys.exc_info()[0])
        sys.exit(message)


def db_initiate_connection(host_name, user_name, password, db_name):
    try:
        db_connection = mysql.connector.connect(
            host=host_name,
            user=user_name,
            password=password,
            database=db_name
        )
        if db_connection.is_connected():
            db_Info = db_connection.get_server_info()
            print("Connected to SQL Server Version ", db_Info)
            return db_connection

    except Error as e:
        message = ("Error when connecting to the database:", e)
        sys.exit(message)


def fetch_data():

    config = load_config()

    Current_Date = str(date.today())
    Previous_Date = str(date.today() - timedelta(days = 1))

    # SQL Query for fetching the JIDs for the specified date
    ## As of now limited to 5 for testing purpose
    #sql_journal_query = "select id from journals where date between '" + Previous_Date + "' and '" + Current_Date +"' limit 5"
    sql_journal_query = "select id from journals where date between '2021-11-04' and '2021-11-05' limit 5"

    # Initiating database connection
    db_connection = db_initiate_connection(
        config['host'], config['user'], config['password'], config['database'])
    
    if db_connection.is_connected():
        
        print("Database connected.")

        # Fetch JIDs for the specified date and save them in a record
        JournalIdCursor = db_connection.cursor()
        print("Journal Cursor created.")
        JournalIdCursor.execute(sql_journal_query)
        
        JID_Record = JournalIdCursor.fetchall()
        print("Total number of JIDs fetched: ", JournalIdCursor.rowcount)
        
        # Closing Journal Cursor
        JournalIdCursor.close()
        print("Journal Cursor is closed.")
        # Closing the data base connection 
        db_connection.close()
        print("Database connection ended.")

        # SQL Query to fetch the expected data for ACE Dashboard
        
        sql_query = 'select cust.name as Customer, j.name as JID, j.aid as JID_AID, r.name as Rule, cat.name as Category, rt.name as Change_Type, prec.find_text as Find, prec.replace_text as "Replace", prec.occurrences as Occurrences, j.date as ProcessedDate from  journals j, rules r, rule_type rt, category cat, precision_entries prec, customer cust where j.customer=cust.id and prec.journal_id=j.id and prec.rule_id=r.id and prec.type_id=rt.id and prec.category_id=cat.id and prec.category_id NOT IN (6,7,8,9) and cust.name!="" and j.id = {}'
        
        # Initiating database connection 
        db_connection = db_initiate_connection(config['host'], config['user'], config['password'], config['database'])

        if db_connection.is_connected():

            print("Database connected.")
            
            finalcursor = db_connection.cursor()
            print("Final Cursor created.")
            
            for x in JID_Record:
                finalcursor.execute(sql_query.format(*x))
                finalrecords = finalcursor.fetchall()
                
                for y in finalrecords:
                    ACE_Data_Array.append(y)

            dataframe = pd.DataFrame(ACE_Data_Array, columns=['Customer', 'JID', 'JID_AID', 'Rule', 'Category', 'Change_Type', 'Find', 'Replace', 'Occurences', 'ProcessedDate'])
            
            # Need to convert the Date and Time as per format/
            # Date - YYYY-MM-DD
            dataframe['ProcessedDate'] = dataframe['ProcessedDate'].astype('datetime64[s]')

            dataframe.to_csv(PATH_TO_CSV, sep=';', encoding='utf=8', index=False)
            print("Fetched data loaded into CSV file.")

            finalcursor.close()
            print("Final Cursor is closed.")
            db_connection.close()
            print("Database connection ended.")
            return dataframe
        
        else:
            print("No database connection found.")
    
    else:
        print("No database connection found.")


def create_hyper_file_from_csv(dataframe):

    print("Load data from CSV into table in new Hyper file for ACE Dashboard")

    process_parameters = {
        # Limits the number of Hyper event log files to two.
        "log_file_max_count": "2",
        # Limits the size of Hyper event log files to 100 megabytes.
        "log_file_size_limit": "100M"
    }

    with HyperProcess(Telemetry.DO_NOT_SEND_USAGE_DATA_TO_TABLEAU, 'Tabloader', parameters=process_parameters) as hyper:

        connection_parameters = {"lc_time": "en_US"}

        with Connection(endpoint=hyper.endpoint, database=PATH_TO_HYPER,
                        create_mode=CreateMode.CREATE_AND_REPLACE, parameters=connection_parameters) as connection:
            
            connection.catalog.create_table(ace_dashboard_table)

            with Inserter(connection, ace_dashboard_table) as inserter:
                for index, row in dataframe.iterrows():
                    try:
                        inserter.add_row(row)
                    except Exception as e:
                        print("An error occured at row {index}: {e}")
                
                inserter.execute()
                
            #insert_csv_data = connection.execute_command(
            # ) command=f"COPY {ace_dashboard_table.table_name} FROM {escape_string_literal(PATH_TO_CSV)} with "
            #    "(format csv, NULL 'NULL', delimiter ';', header true)")

        print("The connection to the Hyper file is closed.")
    #print(f"Loaded {insert_csv_data} rows.")
    os.remove(PATH_TO_CSV)


if __name__ == '__main__':
    try:
        df = fetch_data()
        create_hyper_file_from_csv(df)

    except HyperException as ex:
        print(ex)
        exit(1)

**Comment by ramananravishankar** [comment]
I tried again and still getting the same error stating the file exists already.

Below is the code.

import mysql.connector
import pandas as pd
import csv
import os
import json
import sys
import datetime
from datetime import date, datetime, timedelta
from mysql.connector import Error
from tableauhyperapi import HyperProcess, Connection, TableDefinition, SqlType, Telemetry, Inserter, CreateMode, connection, \
    escape_string_literal, HyperException, NULLABLE, tabledefinition


PATH_TO_CSV = r"ACE_DB_Output_" + str(date.today()) + "_.csv"
PATH_TO_HYPER = r"ACE_DB_Output_.hyper"

ace_dashboard_table = TableDefinition(
    table_name="ACE_Dashboard",
    columns=[TableDefinition.Column('Customer', SqlType.text(), NULLABLE),
             TableDefinition.Column('JID', SqlType.text(), NULLABLE),
             TableDefinition.Column('JID_AID', SqlType.text(), NULLABLE),
             TableDefinition.Column('Rule', SqlType.text(), NULLABLE),
             TableDefinition.Column('Category', SqlType.text(), NULLABLE),
             TableDefinition.Column('Change_Type', SqlType.text(), NULLABLE),
             TableDefinition.Column('Find', SqlType.text(), NULLABLE),
             TableDefinition.Column('Replace', SqlType.text(), NULLABLE),
             TableDefinition.Column('Occurrences', SqlType.int(), NULLABLE),
             TableDefinition.Column('ProcessedDate', SqlType.date(), NULLABLE)
             ]
)

ACE_Data_Array = []

def load_config():
    try:
        with open('config.json', 'r') as f:
            config_file = json.load(f)
            print("Config file loaded.")
            return config_file
    except:
        message = "Could not read config file."
        print("Unexpected error: ", sys.exc_info()[0])
        sys.exit(message)


def db_initiate_connection(host_name, user_name, password, db_name):
    try:
        db_connection = mysql.connector.connect(
            host=host_name,
            user=user_name,
            password=password,
            database=db_name
        )
        if db_connection.is_connected():
            db_Info = db_connection.get_server_info()
            print("Connected to SQL Server Version ", db_Info)
            return db_connection

    except Error as e:
        message = ("Error when connecting to the database:", e)
        sys.exit(message)


def fetch_data():

    config = load_config()

    Current_Date = str(date.today())
    Previous_Date = str(date.today() - timedelta(days = 1))

    # SQL Query for fetching the JIDs for the specified date
    #sql_journal_query = "select id from journals where date between '" + Previous_Date + "' and '" + Current_Date +"' limit 5"

    ## As of now limited to 5 for testing purpose
    sql_journal_query = "select id from journals where date between '2021-11-04' and '2021-11-05' limit 5"

    # Initiating database connection
    db_connection = db_initiate_connection(
        config['host'], config['user'], config['password'], config['database'])
    
    if db_connection.is_connected():
        
        print("Database connected.")

        # Fetch JIDs for the specified date and save them in a record
        JournalIdCursor = db_connection.cursor()
        print("Journal Cursor created.")
        JournalIdCursor.execute(sql_journal_query)
        
        JID_Record = JournalIdCursor.fetchall()
        print("Total number of JIDs fetched: ", JournalIdCursor.rowcount)
        
        # Closing Journal Cursor
        JournalIdCursor.close()
        print("Journal Cursor is closed.")
        # Closing the data base connection 
        db_connection.close()
        print("Database connection ended.")

        # SQL Query to fetch the expected data for ACE Dashboard
        
        sql_query = 'select cust.name as Customer, j.name as JID, j.aid as JID_AID, r.name as Rule, cat.name as Category, rt.name as Change_Type, prec.find_text as Find, prec.replace_text as "Replace", prec.occurrences as Occurrences, j.date as ProcessedDate from  journals j, rules r, rule_type rt, category cat, precision_entries prec, customer cust where j.customer=cust.id and prec.journal_id=j.id and prec.rule_id=r.id and prec.type_id=rt.id and prec.category_id=cat.id and prec.category_id NOT IN (6,7,8,9) and cust.name!="" and j.id = {}'
        
        # Initiating database connection 
        db_connection = db_initiate_connection(config['host'], config['user'], config['password'], config['database'])

        if db_connection.is_connected():

            print("Database connected.")
            
            finalcursor = db_connection.cursor()
            print("Final Cursor created.")
            
            for x in JID_Record:
                finalcursor.execute(sql_query.format(*x))
                finalrecords = finalcursor.fetchall()
                
                for y in finalrecords:
                    ACE_Data_Array.append(y)

            dataframe = pd.DataFrame(ACE_Data_Array, columns=['Customer', 'JID', 'JID_AID', 'Rule', 'Category', 'Change_Type', 'Find', 'Replace', 'Occurences', 'ProcessedDate'])
            
            # Need to convert the Date and Time as per format/
            # Date - YYYY-MM-DD
            dataframe['ProcessedDate'] = dataframe['ProcessedDate'].astype('datetime64[s]')

            dataframe.to_csv(PATH_TO_CSV, sep=';', encoding='utf=8', index=False)
            print("Fetched data loaded into CSV file.")

            finalcursor.close()
            print("Final Cursor is closed.")
            db_connection.close()
            print("Database connection ended.")
            return dataframe
        
        else:
            print("No database connection found.")
    
    else:
        print("No database connection found.")


def create_hyper_file_from_csv(dataframe):

    print("Load data from CSV into table in new Hyper file for ACE Dashboard")

    process_parameters = {
        # Limits the number of Hyper event log files to two.
        "log_file_max_count": "2",
        # Limits the size of Hyper event log files to 100 megabytes.
        "log_file_size_limit": "100M"
    }

    with HyperProcess(Telemetry.DO_NOT_SEND_USAGE_DATA_TO_TABLEAU, 'Tabloader', parameters=process_parameters) as hyper:

        connection_parameters = {"lc_time": "en_US"}

        with Connection(endpoint=hyper.endpoint, database=PATH_TO_HYPER,
                        create_mode=CreateMode.CREATE_AND_REPLACE, parameters=connection_parameters) as connection:
            
            connection.catalog.create_table(ace_dashboard_table)

            with Inserter(connection, ace_dashboard_table) as inserter:
                for index, row in dataframe.iterrows():
                    try:
                        inserter.add_row(row)
                    except Exception as e:
                        print("An error occured at row {index}: {e}")
                
                inserter.execute()
                
            #insert_csv_data = connection.execute_command(
            # ) command=f"COPY {ace_dashboard_table.table_name} FROM {escape_string_literal(PATH_TO_CSV)} with "
            #    "(format csv, NULL 'NULL', delimiter ';', header true)")

        print("The connection to the Hyper file is closed.")
    #print(f"Loaded {insert_csv_data} rows.")
    os.remove(PATH_TO_CSV)


if __name__ == '__main__':
    try:
        df = fetch_data()
        create_hyper_file_from_csv(df)

    except HyperException as ex:
        print(ex)
        exit(1)

**Comment by jonas-eckhardt** [comment]
You are still using `CreateMode .CREATE_AND_REPLACE` in the code, which will overwrite the hyper file. Please try `CreateMode.NONE`.

Another thing that might simplify your process is `pantab`, see here: https://pantab.readthedocs.io/en/latest/

**Comment by ramananravishankar** [comment]
Sorry, I pasted the old code. I have changed it to CreateMode.NONE in the original file.

**Comment by ramananravishankar** [comment]
pantab makes the job very easy. Thank you so much.

**Comment by jonas-eckhardt** [comment]
Sounds great, @ramananravishankar. I'll close the issue. Let me know if you have any further questions. 

Btw, we have a program dedicated to developers using our APIs: https://www.tableau.com/developer

Amongst others, you get slack access to the developer community, Tableau Online beta access and much more.

Cheers
Jonas
