### ISSUE TITLE
Hyper API without Tableau installed

### ISSUE THREAD

**Issue by WowItsDoge** [tableau/hyper-api-samples#49]
Hi,

is it possible to read a Tableau Hyper file with the Hyper API without Tableau installed on the current computer?

I know this is not exactly a question about the examples, but I think the answer would be interesting for others to and couldn´t be found in the documentation.

Regards,
Jan

**Comment by vogelsgesang** [comment]
Yes, HyperAPI is completely independent of any other Tableau products

**Comment by WowItsDoge** [comment]
Thank you for your answer!
It works :)
