### ISSUE TITLE
Unable to leverage multi-table hyper file as dataset for Tableau server.

### ISSUE THREAD

**Issue by stadled-data** [tableau/hyper-api-samples#5]
Was on the Hyper API workshop call on 6/23.  Was suggested to post this here.  

 dont know if this is really a hyper api issue.  But here is how we attempting to leverage it.
I have a data warehouse data mart (fact (140 million rows) with 12 dimensions).  If we attempt to create an extract with Tableau Desktop on current gen macbook pro with 32gb ram it takes about 14 hours ish.  I created a python script that queries and creates csvs from snowflake for the tables in parallel, then parse the schema of the tables and create a multi table hyper file from it.
The goal is to get that hyper file/extract be uploaded for our creators and explorers to look at the data in tableau server.
I then as a test, just opened tableau desktop pointed at the hyperfile, defined the relationships and attempted to upload the tdsx to the server.  My computer than sat for hours and using in the end 100gb of swap and all memory.  Evantually ran out of space on my disk after a couple hours.
Thats a bit of detail that may not be necessary but I want to know am I approaching the problem with the right workflow?

Here is my simple scripts right now.  They need more work but got me to a multi-table hyper file way quicker than using desktop to create an extract with snowflake direct.

[Tableau Extract Automation.zip](https://github.com/tableau/hyper-api-samples/files/4820602/Tableau.Extract.Automation.zip)

**Comment by jonas-eckhardt** [comment]
Thanks for reporting this. 

Can you please double check what exactly did you do in Tableau Desktop to create the TDSX file? I suspect that something went wrong there.

Can you please 
1. Double-click on the .hyper file (or just drag it to Tableau)
2. Model your join
3. Click on Sheet 1
4. Go to Data > [the datasource] > Add to saved datasource
5. Save the file somewhere and select TDSX as type.

The last step may take a long time, as the hyper file will be zipped into the TDSX file.

**Comment by jonas-eckhardt** [comment]
@stadled-data is this still relevant? Otherwise, I'd like to close it.

**Comment by stadled-data** [comment]
We ended up pivoting to a strategy that leveraged a couple components from the server api and community contributions to programmatically push the publish and switch operation.  Sorry for not responding earlier.

**Comment by jonas-eckhardt** [comment]
Thanks @stadled-data for confirming.
