### ISSUE TITLE
Support arm64

### ISSUE THREAD

**Issue by joshuataylor** [tableau/hyper-api-samples#51]
Hi!

I'm trying to install this on arm64, and am getting this error:
```
  Unable to find installation candidates for tableauhyperapi (0.0.14567)
```

Can we get builds for arm64 for linux, so we can run it on Graviton, and for Mac so we can run it on M1?

https://pypi.org/project/tableauhyperapi/#files

tableauserverclient does this for "all"
https://pypi.org/project/tableauserverclient/#files

**Comment by vogelsgesang** [comment]
Thanks for reaching out! :) 

**M1 support** is on our backlog for later this year. Unfortunately, we so far don't have a M1 toolchain, yet, and building for M1 is hence not a simple "just re-compile on M1" for us.

For the time being, you can use HyperAPI on M1 by running under Rosetta2. To do so, you must ensure to use an x86-based Python interpreter (which then also runs under Rosetta2), though. On the Python [download page](https://www.python.org/downloads/macos/), you need to make sure to install one of the "Intel-only installers". Unfortunately, this implies that you can't use Python 3.10 with HyperAPI on macOS, yet.

**Graviton support** is not on our backlog, yet. As an engineer, I am eager to implement it, but we are currently still lacking a business justification for this. (For our own deployments, e.g. in Tableau Online, the cost savings of Graviton don't offset the necessary investments). Can you provide some background on why you want Graviton support?

**Comment by joshuataylor** [comment]
Our current dagster server runs on ARM64, but can also run on AMD64 without problems -- we've just seen great performance and decent costs running on Graviton2.

Our developers run Macs with M1, so installing this repo will be a hard sell as they will have to use rosetta, when everything else runs natively. Is there a binding or something that prohibits using `-any` similar to how tableauserverclient does it? (I'm not a python expert, so my apologies).

**Comment by vogelsgesang** [comment]
> Is there a binding or something that prohibits using -any similar to how tableauserverclient does it?

HyperAPI is not a native Python library. Its "core" is implemented in C++, and hence needs to be compiled for a specific target platform. The Python interface which you are interacting with is just a wrapper around this C-based core.
This is in contrast to tableauserverclient which is a pure Python library.

**Comment by joshuataylor** [comment]
That makes complete sense, cheers. Will wait for the other architectures!
