### ISSUE TITLE
Cannot COPY from a FIFO

### ISSUE THREAD

**Issue by bwlang** [tableau/hyper-api-samples#53]
I tried feeding the COPY command  a bash command subsitution (e.g. ./import.py <(zstd -d < file.zst)) or a manually created  FIFO  (mkfifo import && zstd -d < file.zst > import &; ./import.py import).

The data I'm trying to read in is 90G compressed ... I'm not very excited about decompressing it just to put it back into the .hyper file.    Could the hyper API not try to seek and just stream the data instead?

Here's the error in the hyper log:
```
{"ts":"2022-04-30T14:29:55.586433","pid":28907,"tid":"7ffa337fe700","sev":"error","req":"2","sess":"bg12tJyuSG-bx1p5CskBCw","k":"query-end-system-error","v":{"error-code":"58000","error-message":"unable to read from external source.","error-detail-internal":"source: \"import\"\nsystem error: lseek(): Illegal seek","elapsed":0.0041398,"parsing-time":3.0753e-05,"initial-compilation-time":0.00201559,"execution-time":0.00198987,"exec-threads":{"thread-time":0.00198987,"cpu-time":0.00198974,"wait-time":0,"storage":{}},"peak-transaction-memory-mb":0.25,"time-to-schedule":2.5986e-05,"lock-acquisition-time":6.97e-07,"peak-result-buffer-memory-mb":0,"peak-result-buffer-disk-mb":0,"result-size-mb":2.28882e-05,"statement":"COPY","spooling":false,"query-settings-active":false,"plan-cache-status":"cache miss","plan-cache-hit-count":0,"cols":0,"rows":0,"query-hash":"293c.08f52f363204.623a1f","query-trunc":"COPY \"meth\" from 'import' with (format csv, NULL 'NULL', delimiter '\t')"}}
```

**Comment by jkammerer** [comment]
Hello!

Streaming into Hyper that way is not supported. However, what we do have is an experimental (undocumented) feature called `experimental_external_gzip_compression` that you could set to true in the HyperProcess constructor. Then you can use SQL options for the CSV scan like that: `(format csv, compression 'gzip', delimiter ',')` to directly ingest a gzipped CSV file.
This is only available for gzip at the moment, though. 
Or maybe you consume the stream in your python program yourself and materialize it into small temp files that you then ingest with Hyper. Not sure about the performance of the python part, though.

**Comment by vogelsgesang** [comment]
gzip compression is actually documented and no longer experimental. See https://help.tableau.com/current/api/hyper_api/en-us/reference/sql/external-formats.html#EXTERNAL-OPTION-COMPRESSION
