### ISSUE TITLE
Error converting parquet to hyper

### ISSUE THREAD

**Issue by ImanolR87** [tableau/hyper-api-samples#76]
Failed to start a new Hyper instance.
Context: 0x86a93465

Caused by:
The Hyper server process exited during startup with exit code: 1
        Command-line: ""C:\Users\XXX\AppData\Local\Programs\Python\Python310\lib\site-packages\tableauhyperapi\bin\hyper\hyperd.exe" "run" "--date-style=MDY" "--date-style-lenient=false" "--experimental-external-format-parquet=1" "--init-user=tableau_internal_user" "--language=en_US" "--log-config=file,json,all,hyperd,0" "--log-dir=C:\XXX\XXX" "--no-password=true" "--skip-license=true" "--telemetry-opt-in=" "--listen-connection" "tab.pipe://./pipe/auto" "--callback-connection" "tab.pipe://./pipe/{9F41B5E8-19D8-4E88-A0BE-6852C66DCF87}" "
        Child process' stdout:
        LogFile: \\?\C:\XXX\XXX\hyperd.log

        Child process' stderr:
        Error(s) while applying config file or command line parameters.
        Error. Could not interpret 'experimental_external_format_parquet' as global setting: No internal setting named 'experimental_external_format_parquet' exists.
        Critical setting errors encountered, shutting down.

**Comment by jkammerer** [comment]
From the HyperAPI release notes:

*November 3rd, 2021*
Reading Apache Parquet files is now officially supported and no longer has to be enabled through the use of the process setting experimental_external_format_parquet.

The setting no longer exists, you have to remove it from the parameters you pass to the HyperProcess constructor.
