### ISSUE TITLE
tableauhyperapi (v0.0.16123) HyperException: This database does not support 128-bit numerics.

### ISSUE THREAD

**Issue by Capital-de-dev** [tableau/hyper-api-samples#81]
```
test@local: pip3 list | grep hyper   
tableauhyperapi        0.0.16377 
```

```
What’s New in the Hyper API (v0.0.16123)
December 7, 2022

Added support for 128-bit numerics. This allows a precision of up to 38 for the NUMERIC SQL type.
```

Run:
```
from pathlib import Path

from tableauhyperapi import HyperProcess, Telemetry, \
    Connection, CreateMode, \
    NOT_NULLABLE, NULLABLE, SqlType, TableDefinition, \
    Inserter, \
    escape_name, escape_string_literal, \
    HyperException

customer_table = TableDefinition(
    table_name="Customer",
    columns=[
        TableDefinition.Column("Customer ID", SqlType.text(), NOT_NULLABLE),
        TableDefinition.Column("Customer Amount", SqlType.numeric(38,3), NOT_NULLABLE),
        TableDefinition.Column("Customer Score", SqlType.big_int(), NOT_NULLABLE)
    ]
)

path_to_database = Path("customer.hyper")

with HyperProcess(telemetry=Telemetry.SEND_USAGE_DATA_TO_TABLEAU) as hyper:
    
    connection_parameters = {"lc_time": "en_US"}
    
    with Connection(endpoint=hyper.endpoint,
                        database=path_to_database,
                        create_mode=CreateMode.CREATE_AND_REPLACE,
                        parameters=connection_parameters) as connection:
        
        connection.catalog.create_table(table_definition=customer_table)
```

Output:
```
---------------------------------------------------------------------------
HyperException                            Traceback (most recent call last)
Input In [32], in <module>
     23 connection_parameters = {"lc_time": "en_US"}
     25 with Connection(endpoint=hyper.endpoint,
     26                     database=path_to_database,
     27                     create_mode=CreateMode.CREATE_AND_REPLACE,
     28                     parameters=connection_parameters) as connection:
---> 30     connection.catalog.create_table(table_definition=customer_table)

File ~/.local/lib/python3.8/site-packages/tableauhyperapi/catalog.py:65, in Catalog.create_table(self, table_definition)
     59 def create_table(self, table_definition: TableDefinition):
     60     """
     61     Creates a table. Raise an exception if the table already exists.
     62 
     63     :param table_definition: the table definition.
     64     """
---> 65     self.__create_table(table_definition, True)

File ~/.local/lib/python3.8/site-packages/tableauhyperapi/catalog.py:57, in Catalog.__create_table(self, table_definition, fail_if_exists)
     55 def __create_table(self, table_definition: TableDefinition, fail_if_exists: bool):
     56     native_table_def = SchemaConverter.table_definition_to_native(table_definition)
---> 57     Error.check(hapi.hyper_create_table(self.__cdata, native_table_def.cdata, fail_if_exists))

File ~/.local/lib/python3.8/site-packages/tableauhyperapi/impl/dllutil.py:100, in Error.check(p)
     97 if p != ffi.NULL:
     98     # this will free the error when it goes out of scope
     99     errp = Error(p)
--> 100     raise errp.to_exception()

HyperException: This database does not support 128-bit numerics.
Context: 0xfa6b0e2f
```

**Comment by vogelsgesang** [comment]
Our release notes are confusing... We should fix that.

Hyper API is now able to *read* and *operate* on 128 bit numerics. I.e., if you get a 128 bit numeric e.g. from a Parquet file, you can use normal arithmetic on it. But before you store it into a Hyper file

However, there is not yet any Hyper file format version which allows you to write 128 bit numerics. Such a new file format version is already lined up to ship very soon :)

However, you also have another problem: There is not yet any Tableau version which is able to read 128 bit numerics from Hyper files... Soon 🙂

**Comment by vogelsgesang** [comment]
(Leaving this issue open until we fix our release notes, such that it can be found by others running into this, too)

**Comment by miky-schreiber** [comment]
@vogelsgesang Thank you for this answer, helped us a lot!
Do we have an ETA for a version which will support writing 128 bit numerics into a Hyper file?

**Comment by rajuvg** [comment]
@vogelsgesang  any updates about the version  which will support writing 128 bit numeric to Hyper file?

**Comment by vogelsgesang** [comment]
In fact, there already is a database version 3, similar to the other database versions documented in https://tableau.github.io/hyper-db/docs/hyper-api/hyper_process#databasesettings This database version has been there for a long time already.

Hyper itself would be ready, you can already write database files with 128-bit numerics. The problem is rather: Will Tableau be able to open them? Afaik, more up-to-date versions of Tableau should already be able to do so...

**Comment by rajuvg** [comment]
Thanks for the details, Could you please confirm hyperd version  whichever supports 128 bit decimal and we re running tableau servers version as 2023.1.1

**Comment by vogelsgesang** [comment]
Quoting from the PR linked above:

> The database file format version `3` is supported by Tableau Desktop
2022.4.1 and Server 2023.1 and newer product versions. It is supported by
Tableau Prep 2022.4.1 and newer versions

Does this answer your question?

**Comment by rajuvg** [comment]
Sorry for the confusion  what is the Hyped file version which is used for
creating hyperprocess instance.
Thaks
Raju

**Comment by vogelsgesang** [comment]
Sorry, I don't understand the question.

The hyper file version used to create the HyperProcess instance only influences the files _written_ by that Hyper process.

When it comes to reading (and I assume you are asking about which Tableau versions will be able to read those Hyper files?), then the file format version set as the `default_database_version` has no influence on whether Hyper can read this file or not

**Comment by rajuvg** [comment]
Tableau provided hyperd.exe for widows and hyperd for Linux so that we can
create hyper process in java code and create hyper file.
My question version if hyperd instance will allow us to create hyperfile
with 128but decimal and publish it to tableau server2023.1.1.
Hope my question is clear.
Thanks in advance.
Regards,
Raju

**Comment by rajuvg** [comment]
Thanks by setting the default_database_version:3 helped in publishing 128
bit data where as when I am doing the append it is failing..is this option
supported.
Thanks & Regards
Raju

**Comment by rajuvg** [comment]
Currently we are encountering an issue if we publish a 128 bit hyperfile to
Tableauserver2023.1 with override flag as false, can  you confirm starting
from which version of tableau server this option is supported.Thanks in
advance.
Regards,
Raju

**Comment by vogelsgesang** [comment]
> Thanks by setting the default_database_version:3 helped in publishing 128
bit data where as when I am doing the append it is failing..is this option
supported.

A database file is always using the version which was set during the original creation time of that file. To upgrade to a new version, you need to create a new Hyper file and copy over all your tables from the old file. See https://github.com/tableau/hyper-api-samples/blob/main/Community-Supported/convert-hyper-file/convert_hyper_file.py for an example of how to do so from Python

**Comment by vogelsgesang** [comment]
> [...] if we publish a 128 bit hyperfile to Tableauserver2023.1 with override flag as false,

which exact API call are you using?

**Comment by rajuvg** [comment]
we are using
url=String.format(,overrise=false);
restTemplate.exchange(url,HTTPMethod.post,ent,String.class));
Please let me know if you need more information.

**Comment by rajuvg** [comment]
we are using
url=String.format(,append=true);
restTemplate.exchange(url,HTTPMethod.post,ent,String.class));
Please let me know if you need more information.

**Comment by vogelsgesang** [comment]
I have no idea which Tableau REST API your two source code lines are using.
Please provide a self-contained repro
