### ISSUE TITLE
Issue with Timestamp type when using Hyper extract

### ISSUE THREAD

**Issue by JaronStevenson** [tableau/hyper-api-samples#9]
I created a hyper extract using the Hyper API in Python. This hyper extract contains several Timestamp fields. 

I set the columns to type=SqlType.timestamp() and the data is a Timestamp Object like this: **Timestamp**(_year, month, day, hour, min, sec_).

The issue is when I open the generated hyper extract in Tableau desktop, any back-end date calculations fail, giving the following error:

> An error occurred while communicating with data source 'SN PPM Extract (local copy)'.
> 
> Bad Connection: Tableau could not connect to the data source.
> ERROR:  unsupported data types in call to 'tableau.normalize_datetime'
> 
> SELECT TABLEAU.TO_DATETIME(DATE_TRUNC('YEAR', TABLEAU.NORMALIZE_DATETIME("pm_project"."start_date")), "pm_project"."start_date") AS "tyr:start_date (pm_project):ok"
> FROM "public"."pm_portfolio" "pm_portfolio"
>   LEFT JOIN "public"."pm_project" "pm_project" ON ("pm_portfolio"."name" = "pm_project"."primary_portfolio")
> GROUP BY 1

The above case is using the field 'start_date (pm_project)', and is trying to get the Year part of the date time.

Attached is the .tdsx containing the hyper file as a .zip file. Any help you could provide would be greatly appreciated.

[SN PPM Extract.zip](https://github.com/tableau/hyper-api-samples/files/5042397/SN.PPM.Extract.zip)

**Comment by tsjoblad** [comment]
https://github.com/tableau/hyper-api-samples/blob/d6303a2e3ab2027fcb42ecb3579b966147d3ded8/Tableau-Supported/Python/insert_data_with_expressions.py#L79

Offline, changing over to the expression was recommended

**Comment by JaronStevenson** [comment]
Changed my code over to use the expression for the datetimes and it works like a charm now! Thanks so much! 

Would still like to figure out why exactly using the Timestamp object wasn't working, but this will definitely work as a solution for me. :)
