### ISSUE TITLE
 "'type' must be a SqlType instance"

### ISSUE THREAD

**Issue by Anaisdg** [tableau/hyper-api-samples#91]
Hello, 
I am trying to ingest my parquet file. 
I tried using https://github.com/tableau/hyper-api-samples/blob/9a3ea9c110a87ca27ddf99226837977c69c7dcb5/Community-Supported/parquet-to-hyper/create_hyper_file_from_parquet.py
However when I first tried to use the SqlType.double() I got the following error:
` "'type' must be a SqlType instance"`
Then I converted the type back to int() to see if it would work.
I get the following error now even if I set the type back to double() (which is what I want)
`
unable to read from external source.: Source: "~/Desktop/airSensors.parquet"
Context: 0xfa6b0e2f
`
The part of the example that I changed is: 
```
if __name__ == '__main__':
    try:
        # The `airSensors` table to read from the Parquet file.
        table_definition = TableDefinition(
            table_name="airSensors",
            columns=[
                TableDefinition.Column("co", SqlType.double(), NOT_NULLABLE),
                TableDefinition.Column("humidity", SqlType.double(), NOT_NULLABLE),
                TableDefinition.Column("sensor_ids", SqlType.double(), NOT_NULLABLE),
                TableDefinition.Column("temperature", SqlType.double(), NOT_NULLABLE),
                TableDefinition.Column("time", SqlType.date(), NOT_NULLABLE),
            ]
        )

        run_create_hyper_file_from_parquet(
            "airSensors.parquet",
            table_definition,
            "airSensors.hyper")        
```
Thank you
Is there a better way to load parquet to Tableau?
I'm having trouble finding examples.

**Comment by vogelsgesang** [comment]
> get the following error now [...]:
> `unable to read from external source.: Source: "~/Desktop/airSensors.parquet" Context: 0xfa6b0e2f`

The `~` sign inside that error message looks very suspicious to me. The `~` character is usually already replaced by your shell with the actual path to your home folder. The fact that a `~` ends up in a Hyper error message makes me wonder how it ended up there.

Did you really use

```
        run_create_hyper_file_from_parquet(
            "airSensors.parquet",
            table_definition,
            "airSensors.hyper")   
```

? Or did you by any chance use

```
        run_create_hyper_file_from_parquet(
            "~/Desktop/airSensors.parquet",
            table_definition,
            "airSensors.hyper")
```
 
 or something similar?

**Comment by Anaisdg** [comment]
@vogelsgesang oops I had a type in my source thank you! 
Can you help me with the following error too please? 
```
COPY "airSensors" FROM 'airSensors.parquet' WITH (FORMAT PARQUET)
Type 'double precision' is incompatible to type 'text' of column 'sensor_id' in Parquet file.: Parquet file airSensors.parquet
Context: 0xfa6b0e2f
```
Its showing a dictionary type but I don't see that supported in the docs.  
<img width="619" alt="Screen Shot 2023-03-28 at 11 12 53 AM" src="https://user-images.githubusercontent.com/30506042/228302989-c0152807-067f-4b68-98b4-463fadbab428.png">
